#!/bin/bash

export DOTFILES=$HOME/dotfiles

ln -s $DOTFILES/.zshrc     $HOME/.zshrc
ln -s $DOTFILES/.vimrc     $HOME/.vimrc
ln -s $DOTFILES/.gitignore $HOME/.gitignore
ln -s $DOTFILES/.tmux      $HOME/.tmux
ln -s $DOTFILES/.tmux.conf $HOME/.tmux.conf